# Generated by Django 5.0.6 on 2024-06-20 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_category_options_product_is_sale_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='old_cart',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
