# Generated by Django 5.0.6 on 2024-06-20 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_old_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='old_cart',
        ),
        migrations.AddField(
            model_name='customer',
            name='old_cart',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
