# Generated by Django 5.0.6 on 2024-06-20 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_remove_product_old_cart_customer_old_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='sele_price',
            new_name='sale_price',
        ),
    ]
